site_name: Malinkang's Notes
site_description: 学习笔记
site_url: https://malinkang.github.io/weread/
site_author: malinkang
## Repository
repo_name: malinkang/note
repo_url: https://github.com/malinkang/weread
# Copyright
copyright: Copyright &copy; 2013 - 2023 malinkang

theme:
  name: material
  logo: https://img.icons8.com/ios/250/ffffff/journal.png
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - content.action.edit
  palette:
    - scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: logo
  font:
    text: Roboto
    code: Roboto Mono
    
extra_css:
  - stylesheets/main.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/malinkang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/malinkang
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/malinkang
    - icon: fontawesome/brands/telegram
      link: https://t.me/malinkang
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/malinkang
    - icon: fontawesome/brands/medium
      link: https://medium.com/malinkang
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@malinkang

plugins:
  - tags:
      tags_file: tags.md
  - search
  - callouts
  - git-authors
  - literate-nav:
      tab_length: 2
  - ezlinks:
      wikilinks: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - glightbox
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic

nav:
  - Home: index.md
  - 读书笔记: books/
  - 分类: tags.md