name: backup book
on:
  push:
    branches:
      - backup
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install @notionhq/client
      - run: npm install notion-to-md
      - name: backup book
        run: node scripts/backup.js
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'new backup' || echo "nothing to commit"
          git push || echo "nothing to push"