name: backup book
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create book dir 
        run: |
          mkdir -p backup/docs/books
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install @notionhq/client
      - run: npm install notion-to-md
      - name: backup book
        run: node scripts/backup.js
      - name: push
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
            add: 'backup/docs/books'
            author_name: GitHub Action
            author_email: action@github.com
            new_branch: backup2
    #   - name: push
    #     run: |
    #       cd backup
    #       git config --local user.email "action@github.com"
    #       git config --local user.name "GitHub Action"
    #       git add .
    #       git commit -m '备份' || echo "nothing to commit"
    #       git push origin backup2|| echo "nothing to push"