name: Backup Images

on:
  workflow_dispatch:
  push:
    branches:
      - main # 这是触发备份操作的分支，根据你的需求调整

jobs:
  backup-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: Set default year if not provided
        run: echo "YEAR=$(date +"%Y")" >> $GITHUB_ENV
        if: env.YEAR == ''
      - name: Check if backup branch exists
        id: check-backup
        run: |
          echo "Checking for backup branch..."
          if git ls-remote --heads origin backup; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: Checkout backup branch into backup directory
        if: steps.check-backup.outputs.exists == 'true'
        uses: actions/checkout@v2
        with:
          ref: backup2
          path: backup
      - name: weread heatmap
        run: |
          github_heatmap weread  --weread_cookie "${{secrets.WEREAD_COOKIE}}" --year $YEAR  --me "${{secrets.NAME}}" --with-animation --background-color=${{ vars.background_color||'#FFFFFF'}} --track-color=${{ vars.track_color||'#ACE7AE'}} --special-color1=${{ vars.special_color||'#69C16E'}} --special-color2=${{ vars.special_color2||'#549F57'}} --dom-color=${{ vars.dom_color||'#EBEDF0'}} --text-color=${{ vars.text_color||'#000000'}}
      - name: Rename weread.svg to a random name
        run: |
          RANDOM_FILENAME=$(uuidgen).svg
          mv ./OUT_FOLDER/weread.svg ./OUT_FOLDER/$RANDOM_FILENAME
          echo "Renamed file to $RANDOM_FILENAME"
      - name: Copy images to backup branch directory
        run: |
          rm -rf ./backup/assets/heatmap/
          mkdir -p backup/assets/heatmap/
          cp -r OUT_FOLDER/* backup/assets/heatmap/
      - name: Commit and push to backup branch
        run: |
          cd backup
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/heatmap
          git commit -m "Backup images" -m "Committing images to backup branch" || echo "No changes to commit"
          git branch -M backup2
          git push -u origin backup2
